stages:
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: ntest
      pushRemote: true
      registry: registry.cn-shenzhen.aliyuncs.com
timeout: 60
notification: {}
