stages:
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: timedifier/ntest:${CICD_EXECUTION_SEQUENCE}_${CICD_GIT_TAG}
      pushRemote: true
      registry: registry.cn-hangzhou.aliyuncs.com
timeout: 60
notification: {}
